### ISSUE TITLE
loc2mapbot.php

### ISSUE THREAD

**Issue by DenisKorablove** [mukens/loc2mapbot#1]
require_once "vendor/autoload.php"; ?

**Comment by EvTheFuture** [comment]
Have you executed the prepare script init.sh to install dependencies and install necessary files from the templates?

**Comment by DenisKorablove** [comment]
> Have you executed the prepare script init.sh to install dependencies and install necessary files from the templates?

I have Virtual Hosting ((

**Comment by EvTheFuture** [comment]
> > Have you executed the prepare script init.sh to install dependencies and install necessary files from the templates?
> 
> I have Virtual Hosting ((

Unfortunately you'll need a VPS or a server.

It would also be possible to create a docker image, but then you need somewhere to run that image.

**Comment by DenisKorablove** [comment]
Ok, but tell me what changes to make in order to display users on the map simply, without a game, on leaflet... Please :)

**Comment by EvTheFuture** [comment]
Unfortunately you can't use this code.

You'll have to find something for leaflet. This project provide scripts that are ment to be installed on a server where you have full administrative rights.
